//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Uppmem.rc
//
#define IDC_MECH_CALC_FLUX              6
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_UPPMEMTYPE                  129
#define IDD_MECHANISTIC                 131
#define IDD_EMPIRICAL                   132
#define IDD_DESIGN                      133
#define IDB_HAPPY1                      134
#define IDD_RUN                         135
#define IDD_PARAM_RANGE                 137
#define IDD_ADDTL_PARAMS                139
#define IDD_PREDEF_MEMB                 141
#define IDD_DISTRIB                     142
#define IDD_ERROR                       143
#define IDD_EMP_DATA_ENTER              144
#define IDD_EMP_PICK_MODEL              146
#define IDD_FLUX_RANGE                  147
#define IDD_PERM_PART_DISTRIB_DLG       150
#define IDC_MECH_PRESSURE               1002
#define IDC_MECH_PART_DISTRIBUTION      1003
#define IDC_MECH_MEMSYS_RADIO           1005
#define IDC_MECH_SE_RADIO               1006
#define IDC_MECH_TEMP                   1007
#define IDC_MECH_INFLUENT_FLOW          1008
#define IDC_MECH_VISCOSITY              1009
#define IDC_MECH_AVE_PART_RADIUS        1010
#define IDC_MECH_AVE_PART_CONC          1011
#define IDC_MECH_GEL_RADIO              1012
#define IDC_MECH_RESISTANCE_RADIO       1013
#define ID_MECH_SAVE                    1014
#define IDC_MECH_PORE_RADIUS            1015
#define IDC_MECH_MEMB_RESISTANCE        1016
#define IDC_MECH_MEMB_LENGTH            1018
#define IDC_MECH_MEMB_CHANNEL_RADIUS    1019
#define IDC_MECH_ADDTL_MODEL_PARAMS     1020
#define IDC_MECH_MEMB_AREA              1021
#define IDC_MECH_AVE_PART_DENSITY       1022
#define IDC_MECH_RECIRC                 1023
#define IDC_MECH_FLUX_MS                1049
#define IDC_MECH_FLUX_LH                1050
#define IDC_MECH_PARAM_RANGE            1052
#define IDC_MECH_MEMB_SELECT            1053
#define IDC_RANGE_PRESS_RADIO           1054
#define IDC_RANGE_TEMP_RADIO            1055
#define IDC_RANGE_FLOW_RADIO            1056
#define IDC_RANGE_VISC_RADIO            1057
#define IDC_RANGE_PRESS1                1058
#define IDC_RANGE_TEMP1                 1059
#define IDC_RANGE_FLOW1                 1060
#define IDC_RANGE_VISC1                 1061
#define IDC_RANGE_PRESS2                1062
#define IDC_RANGE_TEMP2                 1063
#define IDC_RANGE_FLOW2                 1064
#define IDC_RANGE_VISC2                 1065
#define IDC_RANGE_NUM_STEPS             1066
#define IDC_RANGE_CONC1                 1067
#define IDC_MECH_AMP_MTC_ESTIMATE_RADIO 1068
#define IDC_RANGE_CONC_RADIO            1068
#define IDC_EMP_EXP_DATA                1069
#define IDC_MECH_AMP_MTC_ENTER_RADIO    1069
#define IDC_RANGE_CONC2                 1069
#define IDC_MECH_AMP_OP_REST            1070
#define IDC_MECH_AMP_MTC                1071
#define IDC_MECH_AMP_IRREV_REST         1072
#define IDC_EMP_PARAM_RANGE             1081
#define IDC_EMP_PRESSURE                1082
#define IDC_EMP_TEMP                    1083
#define IDC_EMP_INFLUENT_FLOW           1084
#define IDC_EMP_VISCOSITY               1085
#define IDC_EMP_CLEAN_TIME              1086
#define IDC_EMP_FLUX_TIME               1087
#define IDC_EMP_AVE_PART_CONC           1088
#define IDC_EMP_PERM_TIME               1089
#define IDC_EMP_CALC_FLUX               1090
#define IDC_EMP_FLUX_MS                 1091
#define IDC_EMP_FLUX_LH                 1092
#define ID_EMP_SAVE                     1093
#define IDC_EMP_CONC_UNITS              1094
#define IDC_MEMB_LIST                   1101
#define IDC_MEMB_NAME                   1104
#define IDC_MEMB_MANFC                  1105
#define IDC_MEMB_VIEW                   1114
#define IDC_MEMB_ENTER                  1115
#define IDC_MEMB_REMOVE                 1116
#define IDC_MEMB_RESISTANCE             1117
#define IDC_MEMB_AREA                   1118
#define IDC_MEMB_CHANNEL_RADIUS         1119
#define IDC_MEMB_LENGTH                 1121
#define IDC_MEMB_PORE_RADIUS            1122
#define IDC_DISTRIB_SIZE                1123
#define IDC_DISTRIB_CONC_MASS           1126
#define IDC_DISTRIB_ENTER               1128
#define IDC_DISTRIB_REMOVE              1129
#define IDC_DISTRIB_VIEW                1130
#define IDC_ERR_MSG3                    1131
#define IDC_ERR_MSG                     1132
#define IDC_MECH_AMP_MGL_RADIO          1132
#define IDC_ERR_MSG2                    1133
#define IDC_MECH_AMP_VOL_RADIO          1133
#define IDC_EMP_ENT_FLUX_DATA           1134
#define IDC_EMP_ENT_PARAM2_DATA         1137
#define IDC_PARTICLE_LIST               1142
#define IDC_EMP_PICK_FOUL_RADIO         1144
#define IDC_EMP_PICK_REST_RADIO         1145
#define IDC_EMP_PICK_SURF_RADIO         1146
#define IDC_EMP_ENT_CONC                1147
#define IDC_EMP_PICK_GEL_RADIO          1147
#define IDC_RANGE_FLUX_LIST             1149
#define IDC_EMP_ENT_TEMP_RADIO          1149
#define IDC_EMP_ENT_PRES                1150
#define IDC_EMP_ENT_VLOS                1151
#define IDC_EMP_ENT_TEMP                1152
#define IDC_EMP_ENT_PARAM2_NAME         1153
#define IDC_EMP_INFO                    1154
#define IDC_EMP_ENT_MGL_RADIO           1167
#define IDC_EMP_ENT_VOL_RADIO           1168
#define IDC_EMP_ENT_TIME_RADIO          1169
#define IDC_RANGE_PARAM_NAME            1170
#define IDC_EMP_ENT_CONC_RADIO          1171
#define IDC_EMP_PARAM_A_NAME            1171
#define IDC_EMP_ENT_PRES_RADIO          1172
#define IDC_RANGE_PARAM_EDIT            1172
#define IDC_EMP_PARAM_A_VAL             1172
#define IDC_EMP_ENT_VLOS_RADIO          1173
#define IDC_RANGE_FLUX_EDIT             1173
#define IDC_EMP_PARAM_C_NAME            1173
#define IDC_EMP_PARAM_B_NAME            1174
#define IDC_EMP_PARAM_B_VAL             1175
#define IDC_EMP_PARAM_C_VAL             1176
#define IDC_EMP_CUST_MODEL_VAL          1178
#define IDC_MECH_CALC_REJECT            1179
#define IDC_PERM_PART_LIST              1184
#define IDC_RETEN_PART_LIST             1185
#define IDC_MECH_AMP_MGL_CGEL           1188
#define IDC_MECH_AMP_VOLFR_CGEL         1189
#define ID_MODEL_MECH                   32777
#define ID_MODEL_EMP                    32778
#define ID_MODEL_DESIGN                 32779
#define ID_MODEL_RUN                    32780

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        151
#define _APS_NEXT_COMMAND_VALUE         32789
#define _APS_NEXT_CONTROL_VALUE         1189
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
