      SUBROUTINE FINDKLA(KLASAF,KLAOND,KL,KG,AW,STC,ST,ML,AT,DL,VL,DIFL,DP,GM,VG,DG,DIFG,HENRYC,SAFFAC,RE,FR,WE,RL,RG,RT)
!MS$ ATTRIBUTES DLLEXPORT, STDCALL::FINDKLA
!MS$ ATTRIBUTES ALIAS:'_FINDKLA@100':: FINDKLA
!MS$ ATTRIBUTES REFERENCE::KLASAF,KLAOND,KL,KG,AW,STC,ST,ML,AT,DL,VL,DIFL,DP,GM,VG,DG,DIFG,HENRYC,SAFFAC,RE,FR,WE,RL,RG,RT

         IMPLICIT DOUBLE PRECISION(A-H,O-Z)
         PARAMETER (MAXCOM=10)

         DOUBLE PRECISION HENRYC,DL,DG,VG,VL,ST,DP,STC,AT,GM,ML,AW,RE,FR,WE,DIFL,KL,DIFG,KG,KLAOND,RL,RG,RT,SAFFAC,KLASAF

      
!CC**** CALCULATE KLA FOR COMPOUND I **********************

        CALL AWCALC(AW,STC,ST,ML,AT,VL,DL,RE,FR,WE)
        CALL ONDAKLPT(KL,ML,AW,VL,DL,DIFL,AT,DP)
        CALL ONDAKGPT(KG,GM,AT,VG,DG,DIFG,DP)
        CALL ONDKLAPT(KLAOND,RL,RG,RT,KL,AW,KG,HENRYC)
        CALL KLACOR(KLASAF,KLAOND,SAFFAC)

      END
