      SUBROUTINE FCN (M, N, X, F)
      IMPLICIT NONE
	INTEGER M, N, I
	INTEGER MAXREV,MAXODE,MAXEQUATN,MAXNTANK
C
	PARAMETER (MAXREV=20)
	PARAMETER (MAXODE=50)
	PARAMETER (MAXNTANK=25)
	PARAMETER (MAXEQUATN=MAXODE*MAXNTANK)
C
      DOUBLE PRECISION X(N), F(M)
      DOUBLE PRECISION CATIONS, ANIONS
C
	INTEGER NMONOACID, NMULTIACID	
	DOUBLE PRECISION ANION_IN_FCN,UNKNOWN_ION
	DOUBLE PRECISION YOIONS(MAXEQUATN), XKE(MAXREV)
C
	COMMON /DATA2/ NMONOACID,NMULTIACID,XKE,UNKNOWN_ION
	COMMON/IONS/ ANION_IN_FCN,YOIONS
C
      ANIONS = ANION_IN_FCN + 10**(-14+X(1))
      DO I = 1, NMONOACID
	   ANIONS = ANIONS + YOIONS(I)*XKE(I)/10**(-X(1))
      ENDDO
      DO I = NMONOACID+1, NMONOACID+NMULTIACID
	   ANIONS = ANIONS + YOIONS(I) + 2*YOIONS(I)*XKE(I)/10**(-X(1))
      ENDDO
      CATIONS = UNKNOWN_ION + 10**(-X(1))
      F(1) = ANIONS-CATIONS
C
      RETURN
      END
