CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C																	  C
C	vbms.f															  C
C																	  C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

	INTEGER N

	DOUBLE PRECISION KS,KD,MUM,Y
	
	DOUBLE PRECISION A,B,C,D,E
	
	DOUBLE PRECISION,DIMENSION(1:10)::QN,QNF,V

	COMMON N
	COMMON KS,KD,MUM,Y
	COMMON A,B,C,D,E 
	COMMON QN,QNF,V
