      SUBROUTINE GETHIVQ(TAG,VQMIN,HENRYC,CINFL,CTOBJ,NUMCOM)
!MS$ ATTRIBUTES DLLEXPORT, STDCALL::GETHIVQ
!MS$ ATTRIBUTES ALIAS:'_GETHIVQ@24':: GETHIVQ
!MS$ ATTRIBUTES REFERENCE::TAG,VQMIN,HENRYC,CINFL,CTOBJ,NUMCOM

         IMPLICIT DOUBLE PRECISION(A-H,O-Z)
         PARAMETER (MAXCOM=10)
         DIMENSION CINFL(MAXCOM),CTOBJ(MAXCOM),HENRYC(MAXCOM),VQMIN(MAXCOM)
         DOUBLE PRECISION CINFL,CTOBJ,HENRYC,VQMIN
         INTEGER*2 NUMCOM,TAG

         TAG = 1

         DO 10, I = 1,NUMCOM
            CALL PT1VQMIN(VQMIN(I),CINFL(I),CTOBJ(I),HENRYC(I))
            IF (VQMIN(TAG).LT.VQMIN(I)) THEN
               TAG = I
            END IF
 10      CONTINUE

      END
