      IMPLICIT REAL *8 (A-M, O-Z) 
	
      INTEGER PSM,PVM,SAM,W1,W2,W3,WM1,WM2,WM3,GC,SF
      INTEGER NTK,NTKP1
      INTEGER NPC,NAB,NAGC,NSC
      INTEGER CBAGC,CBPC,CBAB,CBSC
      CHARACTER NAME*20

      COMMON ABD,AGCD,AGCV,AIRDEN,AIRMW,AIRVIS,ALPHA,
     1       ABBSOT,AGBSOT,CO1,CSAT,E,
     2       H,H2ODEN,H2OVIS,HOXY,KB,
     3       KLAOXY,LOGKOW,MW,OXYDIF,PB,PCD,PV,
     4       PV1,Q,QG1,QG2,QG3,QGGC,QW1,
     5       QVAGC,QVPC,QVSC,QR,QV,
     6       RT1,RT2,RT3,SCBD,SCBV,SUFSOR,SQW,
     7       TATV,T,TQG,VOCDFG,VOCDIF,WNDVRI,
     8       WW1,WW2,WW3,XW1,X0,XR,XPC,XSC,Z1,Z2,Z3

      COMMON CA,CB,CC,CD,TCE2

      COMMON H2OSW,KP1,QE1,SCGPRI,SCLPRI

      COMMON PEPSTP,PERAGC,PERBIO,PERBUB,
     1       PERSP,PERSPA,PERSPB,PERSUF,PERVLA,
     2       PERVLB,PERVLP,PERW1,PERW2,PERW3,PRVLGC,
     3       PEPVOL,PESTAB,PERSPC,PERSPD,PERSPW

      COMMON RSTRPG,RVOLAG,RVOLPRI,RVOLW1,RVOLW2,RVOLW3,
     1       RSORPI,RSOPSC,RSORPW,RSOPSW

      COMMON TPER,TRBIOS,TRBULS,TRORPS,TRSTRP,TRSUFS,
     1       TRVLSA,TRVLSB,TRSVOL,TEFF,TRSTAB,TPERX,TIN,
     2       TRORPW

      COMMON CE2(10),FFRACT(10),XBM(10),ATV(10),QG(10)

      COMMON PSM,PVM,SAM,NAME,W1,W2,W3,WM1,WM2,WM3,GC,SF
      COMMON NTK,NTKP1
      COMMON NPC,NAB,NAGC,NSC
      COMMON CBAGC,CBPC,CBAB,CBSC

