      SUBROUTINE OPTMAL(DL,VL,ST,DG,VG,QW,DP,CF,STC,AT,CINFL,CTOBJ,HENRYC,NUMCOM,PRESD,DIFL,DIFG,SAFFAC,TAG,MULTVQ,CEFFL,ERRORF)
!MS$ ATTRIBUTES DLLEXPORT, STDCALL::OPTMAL
!MS$ ATTRIBUTES ALIAS:'_OPTMAL':: OPTMAL
!MS$ ATTRIBUTES REFERENCE::DL,VL,ST,DG,VG,QW,DP,CF,STC,AT,CINFL,CTOBJ,HENRYC,NUMCOM,PRESD,DIFL,DIFG,SAFFAC,TAG,MULTVQ,CEFFL,ERRORF

         IMPLICIT DOUBLE PRECISION(A-H,O-Z)
         PARAMETER (MAXCOM=10,MAXMLT=20)
         DIMENSION CINFL(MAXCOM),CTOBJ(MAXCOM)
         DIMENSION HENRYC(MAXCOM),VQMIN(MAXCOM),DIFL(MAXCOM)
         DIMENSION KL(MAXCOM),DIFG(MAXCOM),KG(MAXCOM),KLAOND(MAXCOM)
         DIMENSION RL(MAXCOM),RG(MAXCOM),RT(MAXCOM),KLASAF(MAXCOM)
         DIMENSION CS(MAXCOM),CEFFL(MAXCOM),PRESDR(MAXCOM)
         DIMENSION DIFF(MAXCOM)

DOUBLE PRECISION QW,CINFL,CTOBJ,HENRYC,DL,DG,VG,VL,ST
DOUBLE PRECISION DP,CF,STC,AT,VQMIN,VQ,QA,PRESD,GM,ML
DOUBLE PRECISION AREA,DT,AW,RE,FR,WE,DIFL,KL,DIFG,KG
DOUBLE PRECISION KLAOND,RL,RG,RT,SAFFAC,KLASAF,CS,HTU
DOUBLE PRECISION NTU,HLL,TV,CEFFL,PRESDR,DIFF,DIFFMX
DOUBLE PRECISION MULTVQ,ACTMLT
         INTEGER NEWTAG,NUMIT,HITAG,VQTAG,NUMMLT
         INTEGER*2 NUMCOM,TAG,ERRORF


!CC**** GET COMPOUND WITH HIGHEST MINIMUM AIR TO WATER RATIO,
!CC**** IDENTIFIED BY TAG (THE NO. OF THE COMPOUND IN ARRAY)

!c         CALL GETHIVQ(TAG,VQMIN,HENRYC,CINFL,CTOBJ,NUMCOM)
         HITAG = TAG

!CC*****************************************************************

         MULTVQ = 3.50D0
         VQTAG = TAG
         NUMMLT = 1

5        NUMIT = 1

!CC**** CALCULATE TOWER DIAMETER AFTER CALCULATING NECESSARY OTHER STUFF

10       NUMIT=1
!c			CALL VQMLTPT1(VQ,VQMIN(VQTAG),MULTVQ)
!c         CALL GETMULT(ACTMLT,VQ,VQMIN(TAG))
!c         CALL AIRFLO(QA,VQ,QW)
!c         CALL PT1LDAIR(GM,PRESD,VQ,DG,DL,CF,VL)
!c         CALL PT1LDH2O(ML,VQ,DG,DL,GM)
!c         CALL PT1AREA(AREA,QW,DL,ML)
!c         CALL PT1DTOW(DT,AREA)

!CC*****************************************************************


!CC**** CALCULATE KLA FOR THE DESIGN COMPOUND **********************

         I = TAG

!c         CALL FINDKLA(KLASAF(I),KLAOND(I),KL(I),KG(I),AW,STC,ST,ML,AT,DL,VL,DIFL(I),DP,GM,VG,DG,DIFG(I),HENRYC(I),SAFFAC,RE,FR,WE,RL(I),RG(I),RT(I))        
			

!CC**** CALCULATE TOWER LENGTH FOR THE DESIGN COMPOUND **************

!c         CALL GETCSPT(CS(TAG),VQ,HENRYC(TAG),CINFL(TAG),CTOBJ(TAG))
!c         CALL GETHTUPT(HTU,QW,AREA,KLASAF(TAG))
!c         CALL GETNTUPT(NTU,CINFL(TAG),CTOBJ(TAG),CS(TAG))
!c         CALL PT1HTOW(HLL,HTU,NTU)
!c         CALL PT1TVOL(TV,AREA,HLL)


!CC**** CALCULATE REMOVAL OF OTHER COMPOUNDS
!CC**** FOR GIVEN DESIGN

         CEFFL(TAG) = CTOBJ(TAG)
         DIFFMX = 0.0D0 
         NEWTAG = TAG

         DO 100, I = 1,TAG-1
!            CALL FINDKLA(KLASAF(I),KLAOND(I),KL(I),KG(I),AW,STC,ST,ML,AT,DL,VL,DIFL(I),DP,GM,VG,DG,DIFG(I),HENRYC(I),SAFFAC,RE,FR,WE,RL(I),RG(I),RT(I))
!            CALL EFFLPT2(CEFFL(I),VQ,HENRYC(I),QW,AREA,HLL,KLASAF(I),CINFL(I))
            DIFF(I) = (CEFFL(I) - CTOBJ(I))/CINFL(I)
            IF (DIFF(I).GT.DIFFMX) THEN
                DIFFMX = DIFF(I)
                NEWTAG = I
            END IF
100      CONTINUE

         DO 110, I = TAG+1,NUMCOM
!            CALL FINDKLA(KLASAF(I),KLAOND(I),KL(I),KG(I),AW,STC,ST,ML,AT,DL,VL,DIFL(I),DP,GM,VG,DG,DIFG(I),HENRYC(I),SAFFAC,RE,FR,WE,RL(I),RG(I),RT(I))
!            CALL EFFLPT2(CEFFL(I),VQ,HENRYC(I),QW,AREA,HLL,KLASAF(I),CINFL(I))
            DIFF(I) = (CEFFL(I) - CTOBJ(I))/CINFL(I)
            IF (DIFF(I).GT.DIFFMX) THEN
               DIFFMX = DIFF(I)
               NEWTAG = I
            END IF

110      CONTINUE

         IF (NUMIT.GE.NUMCOM) THEN
            MULTVQ = MULTVQ + 0.5D0
            NUMMLT = NUMMLT + 1
            IF (NUMMLT.GT.MAXMLT) GOTO 200
            GOTO 5
         END IF

         IF (NEWTAG.NE.TAG) THEN
            TAG = NEWTAG
            VQTAG = TAG
            NUMIT = NUMIT + 1
            GOTO 10
         END IF

!CC****  WE CONVERGED AND WILL EXIT GRACEFULLY

         ERRORF = 0
         RETURN

!CC****  WE DID NOT CONVERGE BUT WILL NOW EXIT THE PROGRAM, CHOOSING
!CC****  TAG BETWEEN ONE OF THE COMPOUNDS OSCILLATING TOWARD BEING
!CC****  THE DESIGN COMPOUND

200      ERRORF = -1
         RETURN

      END
