Attribute VB_Name = "ErrorMod"
Global ErrorMsg(-200 To 200) As String

Sub LoadErrorMessages()
    'This subroutine will read error messages needed by StEPP
    'from a file called errcodes.txt

ErrorMsg(1) = "Temperature at which vapor pressure was calculated is out of the valid temperature range for the applicable vapor pressure equation."
ErrorMsg(2) = "Vapor pressure only available at a discrete temperature.  This may affect the validity of UNIFAC Henry's constants at temperatures differing from the vapor pressure temperature."
ErrorMsg(3) = "Temperature at which liquid density was calculated is out of the valid temperature range for the applicable liquid density equation."
ErrorMsg(4) = "Molecular weight is less than 1000 and the equation of Polson (1950) is generally only valid for molecular weights greater than 1000."
ErrorMsg(5) = "Hayduk & Laudie equation generally applies for molecular weights less than 1000 and for molar volumes between 0.015 and 0.5 m^3/kmol.  Current molecular weight is too large and current molar volume is too small."
ErrorMsg(6) = "Hayduk & Laudie equation generally applies for molecular weights less than 1000 and for molar volumes between 0.015 and 0.5 m^3/kmol.  Current molecular weight and molar volume are both too large."
ErrorMsg(7) = "Hayduk & Laudie equation generally applies for molecular weights less than 1000 and for molar volumes between 0.015 and 0.5 m^3/kmol.  Current molecular weight is too large."
ErrorMsg(8) = "Hayduk & Laudie equation generally applies for molecular weights less than 1000 and for molar volumes between 0.015 and 0.5 m^3/kmol.  Current molar volume is too small."
ErrorMsg(9) = "Hayduk & Laudie equation generally applies for molecular weights less than 1000 and for molar volumes between 0.015 and 0.5 m^3/kmol.  Current molar volume is too large."
ErrorMsg(10) = "Saturation pressure exceeds 1 atm."
ErrorMsg(11) = "Temperature at which water density was calculated is out of the valid temperature range for the water density correlation used."
ErrorMsg(-1) = "No vapor pressure is available in the database."
ErrorMsg(-2) = "No. of UNIFAC subgroups exceeds 20.  Therefore, infinite dilution activity coefficient can not be determined by UNIFAC."
ErrorMsg(-3) = "One or more UNIFAC parameters are missing.  Therefore, infinite dilution activity coefficient can not be determined by UNIFAC.  Try using a different database to get binary interaction parameters."
ErrorMsg(-4) = "No vapor pressure is available in the database.  No. of UNIFAC subgroups exceeds 20.  Therefore, infinite dilution activity coefficient can not be determined by UNIFAC."
ErrorMsg(-5) = "No vapor pressure is available in the database.  One or more UNIFAC parameters are missing.  Therefore, infinite dilution activity coefficient can not be determined by UNIFAC."
ErrorMsg(-6) = "Problem with calculating molecular weight."
ErrorMsg(-7) = "Problem with calculating molar volume at the normal boiling point with Schroeder's method."
ErrorMsg(-8) = "Problem with the equation for Vapor Pressure from the database.  No value could be calculated."
ErrorMsg(-9) = "Problem with the equation for Vapor Pressure from the database.  No value could be calculated.  No. of UNIFAC subgroups exceeds 20.  Therefore, infinite dilution activity coefficient can not be determined by UNIFAC."
ErrorMsg(-10) = "Problem with the equation for Vapor Pressure from the database.  No value could be calculated.  One or more UNIFAC parameters are missing.  Therefore, infinite dilution activity coefficient can not be determined by UNIFAC."
ErrorMsg(-11) = "Problem with the equation for Liquid Density from the database.  No value could be calculated."
ErrorMsg(-12) = "No liquid density is available in the database."
ErrorMsg(-13) = "Liquid density from group contribution at the operating T can't be calculated because molar volume at the normal boiling point is not available."
ErrorMsg(-14) = "Molar Volume at the operating temperature cannot be calculated from the database because Liquid Density is not available in the database."
ErrorMsg(-15) = "Molar Volume at the operating temperature can not be calculated from group contribution method because Liquid Density is not available from group contribution method."
ErrorMsg(-16) = "Normal boiling point is not available in the database."
ErrorMsg(-17) = "Refractive index is not available in the database"
ErrorMsg(-18) = "Problem with calculating aqueous solubility.  Solubility algorithm failed to converge after IMAX iterations.  It's possible the compound is infinitely miscible."
ErrorMsg(-19) = "Problem with calculating aqueous solubility.  Division underflow occurred in Newton's algorithm.  Solubility can not be calculated in this case."
ErrorMsg(-20) = "Problem with calculating aqueous solubility."
ErrorMsg(-21) = "Problem with calculating aqueous solubility."
ErrorMsg(-22) = "Aqueous Solubility is not available in database."
ErrorMsg(-23) = "Problem with calculating octanol water partition coefficient."
ErrorMsg(-24) = "Problem with calculating octanol water partition coefficient."
ErrorMsg(-25) = "Problem with calculating octanol water partition coefficient."
ErrorMsg(-26) = "Problem with calculating octanol water partition coefficient."
ErrorMsg(-27) = "Problem with calculating octanol water partition coefficient."
ErrorMsg(-28) = "Problem with calculating octanol water partition coefficient."
ErrorMsg(-29) = "Problem with calculating octanol water partition coefficient."
ErrorMsg(-30) = "Problem with calculating octanol water partition coefficient."
ErrorMsg(-31) = "Octanol water partition coefficient is not available in the database."
ErrorMsg(-32) = "Can not calculate liquid diffusivity from the Hayduk & Laudie correlation because molar volume at the normal boiling point is unavailable."
ErrorMsg(-33) = "Can not calculate liquid diffusivity from the Wilke-Chang correlation because molar volume at the normal boiling point is not available."
ErrorMsg(-34) = "Can not calculate gas diffusivity from the Wilke-Lee Modification of the Hirschfelder-Bird-Spotz method because molar volume at the normal boiling point is unavailable."
ErrorMsg(-35) = "Unable to regress data points for Henry's constant because the number of Henry's constants in the database is less than 2."
ErrorMsg(-36) = "No UNIFAC parameter sets are available for this compound."
ErrorMsg(-37) = "Temperature is out of the valid temperature range for the DIPPR801 Liquid Density equation.  Therefore, liquid density can not be obtained from DIPPR801."
ErrorMsg(-38) = "Henry's Constant cannot be calculated from UNIFAC because vapor pressure is unavailable."
ErrorMsg(-39) = "Henry's Constant cannot be calculated from UNIFAC because infinite dilution activity coefficient is unavailable."
ErrorMsg(-40) = "Henry's Constant cannot be calculated from UNIFAC because neither vapor pressure nor infinite dilution activity coefficient is available."
ErrorMsg(-41) = "The routine to fit the UNIFAC curve with a data point for Henry's constant cannot be used in this case."
ErrorMsg(-42) = "Molecular Weight is not currently available in the StEPP database."
ErrorMsg(-43) = "Liquid Density from the database cannot be calculated in the proper units of kg/m3 because Molecular Weight is not available.  Therefore, liquid density is unavailable from the database."
ErrorMsg(-44) = "Aqueous Solubility is unavailable in the StEPP database.  Consequently, it is not possible to calculate a value from UNIFAC at the database T."
ErrorMsg(-45) = "The routine to fit the UNIFAC curve with a data point for Aqueous Solubility cannot be used in this case."
ErrorMsg(-46) = "Octanol Water Partition Coefficient is unavailable in the StEPP database.  Consequently, it is not possible to calculate a value from UNIFAC at the database T."
ErrorMsg(-47) = "Can not calculate Liquid Diffusivity from the method of Polson because molecular weight is unavailable."
ErrorMsg(-48) = "Can not calculate gas diffusivity from the Wilke-Lee Modification of the Hirschfelder-Bird-Spotz method because normal boiling point is unavailable."
ErrorMsg(-49) = "Can not calculate gas diffusivity from the Wilke-Lee Modification of the Hirschfelder-Bird-Spotz method because molecular weight is unavailable."
ErrorMsg(-50) = "Can not calculate gas diffusivity from the Wilke-Lee Modification of the Hirschfelder-Bird-Spotz method because molar volume at the normal boiling point and normal boiling point are unavailable."
ErrorMsg(-51) = "Can not calculate gas diffusivity from the Wilke-Lee Modification of the Hirschfelder-Bird-Spotz method because molar volume at the normal boiling point and molecular weight are unavailable."
ErrorMsg(-52) = "Can not calculate gas diffusivity from the Wilke-Lee Modification of the Hirschfelder-Bird-Spotz method because normal boiling point and molecular weight are unavailable."
ErrorMsg(-53) = "Can not calculate gas diffusivity from the Wilke-Lee Modification of the Hirschfelder-Bird-Spotz method because molar volume at the normal boiling point, normal boiling point, and molecular weight are unavailable."
ErrorMsg(-54) = "Can not calculate Henry's Constant from current Vapor Pressure and Activity Coefficient values."
ErrorMsg(-55) = "Can not calculate Molar Volume at Operating T, Molecular Weight is unavailable."
ErrorMsg(-100) = "This routine has not been implemented yet."
ErrorMsg(-200) = "Error while performing calculation in FORTRAN routines."

End Sub

